### ISSUE TITLE
Ch.4 p.113 (4.78)式のp(x) がわからない

### ISSUE THREAD

**Issue by masaki-hamada** [Ttsoccer/Machine-Learning-Discussion#10]
<img src="https://latex.codecogs.com/gif.latex?\mathbf{\varepsilon}&space;\sim&space;\mathcal{N}(\mathbf{0},&space;\frac{1}{\lambda}I_{D-2})" title="\mathbf{\varepsilon} \sim \mathcal{N}(\mathbf{0}, \frac{1}{\lambda}I_{D-2})" />
のとき (4.77)式の D-2 × D 行列 L を使って
<img src="https://latex.codecogs.com/gif.latex?L\mathbf{x}&space;=&space;\varepsilon" title="L\mathbf{x} = \varepsilon" />
とするとなぜ
<img src="https://latex.codecogs.com/gif.latex?p({\bf&space;x})&space;=&space;\mathcal{N}({\bf&space;0},&space;(\lambda^2L^\top&space;L)^{-1})" title="p({\bf x}) = \mathcal{N}({\bf 0}, (\lambda^2L^\top L)^{-1})" />
となるのかがわからない……  
(λ^2 は λ が正しい気がする<br>
そもそも、ε = 0 と考えても Lx = 0 は (x_1, ..., x_D) が等差数列になるという制限しか加えないので p(x) の平均は必ずしも 0 にはならないはず  
なので(4.78)式には飛躍がある気がする
<br><br>
あと L = [L_1, L_2] と分けて条件付き分布を導いてるけどそれは右側の点たちから左側の点たちを予測することになるので図 4.10 のように点と点の間を予測したければ L の列を適当に入れ替えないといけない気がする

**Comment by hamada-masaki** [comment]
p(x)の導出、こうすればできる気がした

----

Lx=ε の式で、D-2次元のεを縦に拡張して(x_1, x_2, ε^T)^T とする
するとLも(D-2)×DからD×D行列になって、上から2行に(1,0,0,...)と(0,1,0,...)が増える
するとこの拡張されたLは正則で、特に行列式が1なので確率分布の変数変換がかんたんにできる
ただし、そうするとp(x_1, x_2, ε)を決めないといけないわけだけど、xとεは独立として
p(x_1, x_2, ε) = p(x_1, x_2)p(ε)
とし、さらにx_1とx_2にimproper prior
p(x_1, x_2) ∝ 1
を仮定すれば同じ式が得られると思う

**Comment by hamada-masaki** [comment]
会社用アカウントでコメントしてしまった
