### ISSUE TITLE
誤植置き場

### ISSUE THREAD

**Issue by alnoivmee** [Ttsoccer/Machine-Learning-Discussion#7]
Ch.2 p.34 (2.30)式：
【誤】mean = θ -> 【正】mean = nθ
くっっっっそ細かいですが時間取られてむかついたので

**Comment by masaki-hamada** [comment]
Ch.4 p.120 (4.128)式の下
A=1_N (転置は不要で縦ベクトルが正しい)

**Comment by masaki-hamada** [comment]
Ch.4 p.102 (4.32)式
クラスごとに共分散行列 <img src="https://latex.codecogs.com/gif.latex?\Sigma_c" title="\Sigma_c" /> が(一般には)異なると仮定しているので argmin の後ろには <img src="https://latex.codecogs.com/gif.latex?\log|\Sigma_c|" title="\log|\Sigma_c|" /> もつくはず
(すぐ下にちゃんと事後確率書いてあるけど)

**Comment by masaki-hamada** [comment]
<img src="https://latex.codecogs.com/gif.latex?\Sigma_c" title="\Sigma_c" />

**Comment by masaki-hamada** [comment]
Ch. 4 p.106 (4.52)式
第2項の <img src="https://latex.codecogs.com/gif.latex?{\bf&space;x}" title="{\bf x}" /> は <img src="https://latex.codecogs.com/gif.latex?{\bf&space;x}_i" title="{\bf x}_i" /> が正しい

**Comment by masaki-hamada** [comment]
Ch.4 p.113 (4.75)式
j は D-2 までではなく D-1 まで

**Comment by masaki-hamada** [comment]
Ch. 4 p.122 (4.142)式の直前
前の節と同じことをやるなら、各 y_i と x の次元を D としたときに (DN)次元ベクトル
<img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;\mathbf{y}_1&space;\\&space;\vdots&space;\\&space;\mathbf{y}_N&space;\end{bmatrix}" title="\begin{bmatrix} \mathbf{y}_1 \\ \vdots \\ \mathbf{y}_N \end{bmatrix}" />
を考えて、Aは (DN)×D 行列
<img src="https://latex.codecogs.com/gif.latex?A&space;=&space;\begin{bmatrix}&space;I_D&space;\\&space;\vdots&space;\\&space;I_D&space;\end{bmatrix}" title="A = \begin{bmatrix} I_D \\ \vdots \\ I_D \end{bmatrix}" />
としないといけない気がする  
(I_D はD×D単位行列)

**Comment by masaki-hamada** [comment]
Ch. 4 p.126 (4.162)式の後
<img src="https://latex.codecogs.com/gif.latex?S&space;\sim&space;\mathrm{Wi}(\Sigma,&space;1)" title="S \sim \mathrm{Wi}(\Sigma, 1)" />
ではなく
<img src="https://latex.codecogs.com/gif.latex?S&space;\sim&space;\mathrm{Wi}(\Sigma,&space;N)" title="S \sim \mathrm{Wi}(\Sigma, N)" />

**Comment by masaki-hamada** [comment]
Ch. 4 p.126 (4.165)式の前
Σ ∼ IW(S^{−1},ν + D +1)
ではなく
Σ ∼ IW(S^{−1},ν)

このあとのページでも逆ウィシャート分布が(4.165)式で定義されてたり S が S^{-1} になった版で定義されてたりややこしい
(よく知らないのでどっちが標準的かわからない、ちなみに英語のWikipedia は S が S^{-1} になった版で定義されている)
