### ISSUE TITLE
Ch.21.3.1 p.737 下限L(q)のq_jに関する項についてまとめられない件 #7

### ISSUE THREAD

**Issue by takiko-san** [Ttsoccer/Machine-Learning-Discussion#8]
全然違う場所なので分かる人がいればで大丈夫です

変分ベイズのお勉強しようとしたら、下限L(q)をq_jについて整理できませんでした😟

式(21.30)から式(21.31)の第2項の変形ってどうなってるんでしょうか...
-\sum_{x_j} log q_j(x_j)・・・[\sum_{k not j} log q_k(x_k) + log q_j(x_j)]
（多分最後のq_j(x_j)にlogがついてないけどその誤植はさておいて）なんでこれをq_jについてまとめると
-\sum_{x_j} q_j(x_j) log q_j(x_j)
となって他が全部定数扱いできるのかわからんです😟

**Comment by shoKagami** [comment]
解答に関係ないけど、数式入力のサンプル

<img src="https://latex.codecogs.com/gif.latex?\sum_{x_j}log&space;q_j(x_j)">

**Comment by masaki-hamada** [comment]
数式かけたのか知らなかった…
```math
1 = 2
```

**Comment by masaki-hamada** [comment]
ちゃんとよんでないからわからないけど、  ~~xの和はデータについて和をとって(x \in D)
q_j は x の次元について和をとっているとするなら、 x_j に関する和とか x_{-j}に関する和の意味がよくわからない
(シグマ記号の和をちゃんと書いてほしい…)~~ かんちがいでした

**Comment by masaki-hamada** [comment]
http://machine-learning.hatenablog.com/entry/2016/01/23/123033
このブログで2次元の場合を扱ってるから参考になりそう
(著者の須山さんはMLPシリーズの教科書など書いているひと)
murphyはxに関する和で書いているところをブログでは積分で書いている

<img src="https://latex.codecogs.com/gif.latex?\sum_{x_{-j}}"> は<img src="https://latex.codecogs.com/gif.latex?{x_j}">以外の変数で積分するってこと

---
多分これで説明できているのでは…

<img src="https://latex.codecogs.com/gif.latex?-\sum_{x_j}q_j(x_j)\sum_{x_{-j}}\prod_{i\neq&space;j}q_i(x_i)[\sum_{k\neq&space;j}\log&space;q_k(x_k)+\log&space;q_j(x_j)]">
は大括弧の中身で2つの項にわけられるけど、第1項は
<img src="https://latex.codecogs.com/gif.latex?\sum_{x_j}q_j(x_j)=1">
なので q_j によらなくなるため、定数にできる。

第2項は
<img src="https://latex.codecogs.com/gif.latex?\sum_{x_{-j}}\prod_{i\neq&space;j}q_i(x_i)=1">
を使うと式(21.31)になる

**Comment by takiko-san** [comment]
あーー、わかった！ありがとう！

たしかに、シグマ使って記述してるのマ－フィーくらいだった
